apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: amb1iwwp3-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-31fb2975d8.6kgv.p3.openshiftapps.com/rhtap/rhtap-qe:61cc70f3c76a54e6e2f1d46ea4c51028324f877e@sha256:35fe0c0af538f56db1bc28f94aea6556e8d529162bbb4f3c35378af23d71572e
        name: container-image  
